language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
  - mvn package
  - docker images
  - docker info
  - docker push schoofskelvin/dapps-destinationservice